### ISSUE TITLE
Does not work without go in PATH

### ISSUE THREAD

**Issue by abergmeier-dsfishlabs** [noonat/sublime-gofmt#5]
I do not have go in my PATH and thus get the error:
```

Traceback (most recent call last):
  File "gofmt in /home/user/.config/sublime-text-3/Installed Packages/Gofmt.sublime-package", line 233, in run_formatter
  File "gofmt in /home/user/.config/sublime-text-3/Installed Packages/Gofmt.sublime-package", line 144, in __init__
  File "gofmt in /home/user/.config/sublime-text-3/Installed Packages/Gofmt.sublime-package", line 144, in <listcomp>
  File "gofmt in /home/user/.config/sublime-text-3/Installed Packages/Gofmt.sublime-package", line 68, in __init__
AttributeError: 'module' object has no attribute 'subprocess_info'
```
Would be good to have a way to specify, which Go binary to use for the fmt call.
When changing settings to:

```
{
  "cmds": [
    ["/home/user/bin/gofmt", "-e", "-s"]
  ],
}
```

the next error is:

```
Traceback (most recent call last):
  File "gofmt in /home/andreas/.config/sublime-text-3/Installed Packages/Gofmt.sublime-package", line 233, in run_formatter
  File "gofmt in /home/andreas/.config/sublime-text-3/Installed Packages/Gofmt.sublime-package", line 144, in __init__
  File "gofmt in /home/andreas/.config/sublime-text-3/Installed Packages/Gofmt.sublime-package", line 144, in <listcomp>
  File "gofmt in /home/andreas/.config/sublime-text-3/Installed Packages/Gofmt.sublime-package", line 70, in __init__
  File "/home/andreas/.config/sublime-text-3/Packages/golangconfig/all/golangconfig.py", line 227, in subprocess_info
    raise exception
golangconfig.EnvVarError: The following environment variable is currently unset: GOPATH
```

**Comment by noonat** [comment]
I use golangconfig to run the go binaries. It supports overriding the PATH it uses, and has examples in the [user documentation](https://github.com/golang/sublime-config/blob/master/docs/user.md). As its intent is to normalize configuration across Golang packages for Sublime, I’d rather not deviate from its established way of doing things. Could you take a look at the docs and see if that gets things working?

**Comment by noonat** [comment]
I'm going to assume this was fixed, closing the issue.

**Comment by grahamjenson** [comment]
This is not fixed and still is an issue.
